project:
  type: website

format:
  html:
    fontsize:  "1.0em"
    theme:
      light: cosmo
      dark: slate
    css: styles.css
    toc: true
    toc-depth: 5
    email-obfuscation: javascript
    smooth-scroll: true
    #backgroundcolor: black
    code-link: true
    #code-block-bg: "#29465B"
    code-line-numbers: "true"
    code-overflow: "wrap" 

execute:
  cache: true
  freeze: true

filters:
  - lightbox
lightbox: auto

highlight-style: breezedark

website:
  title: albertprofe wiki
  #cookie-consent:
  #  type: express
  #  style: headline
  #  palette: dark

  repo-url: https://github.com/Albertprofe/wiki
  repo-actions: [edit, issue]

  navbar:
    background: secondary
    style: "floating"
    search: true
    
    right:
      - text: Home
        file: index.qmd
      - sidebar:linux
      - sidebar:devops
      - sidebar:markup
      - sidebar:javase
      - sidebar:spring   
      - sidebar:reactjs
      - sidebar:scrum
      - sidebar:vocabulary
      - sidebar:ifcd
      - sidebar:about

  sidebar:
    - id: "linux"
      title: "Linux OS" 
      border: true
      collapse-level: 1
      background: none
      style: "floating"
      contents: 
        - text: "Linux OS"
        - text: "---"  
        - section: "Linux: concepts"
          contents: 
            - linux/linux-what-basics.qmd
            - linux/linux-what-bash.qmd
            - linux/linux-what-sudo.qmd
            - linux/linux-what-pipes.qmd
            - linux/linux-what-fsys.qmd
            - linux/linux-what-vm.qmd
        - text: "---"  
        - section: "Linux: distros"
          contents: 
            - linux/linux-distros-ubuntu.qmd
            - linux/linux-distros-mint.qmd
            - linux/linux-distros-debian.qmd
            - linux/linux-distros-opensuse.qmd
            - linux/linux-distros-manjaro.qmd
            - linux/linux-distros-redhat.qmd
        - text: "---"  
        - section: "Linux: laboratories"
          contents: 
            - linux/lilab01-1.qmd
            - linux/lilab01-2.qmd
            - linux/lilab01-3.qmd
            - linux/lilab02-1.qmd
            - linux/lilab03-1.qmd
            - linux/lilab03-2.qmd
            - linux/lilab03-3.qmd
            - linux/lilab03-4.qmd
            - linux/lilab04-1.qmd
            - linux/lilab04-2.qmd
            - linux/lilab04-3.qmd
        - text: "---"  
        - section: "Linux readings"
          contents: 
            - linux/resources.qmd

    - id: "devops"
      title: "DevOps" 
      contents:
        - text: "DevOps"
        - text: "---"  
        - section: "What is DevOps"
          contents: 
            - devops/devops-what-intro.qmd
            - devops/devops-what-overview.qmd
            - devops/devops-what-immutable.qmd
        - text: "---"  
        - section: "Documentation"
          contents: 
            - devops/devops-doc-quarto.qmd
        - text: "---"  
        - section: "Version Control"
          contents: 
            - devops/devops-vc-git.qmd
            - devops/devops-vc-github.qmd
        - text: "---" 
        - section: "IDEs"
          contents: 
            - devops/devops-ide-visualcode.qmd
            - devops/devops-ide-intelljidea.qmd
        - text: "---"           
        - section: "DevOps tools"
          contents:
            - devops/devops-tools-aws.qmd
            - devops/devops-tools-docker.qmd
            - devops/devops-tools-jenkins.qmd
            - devops/devops-tools-k8s.qmd
            - devops/devops-tools-digitalocean.qmd
            - devops/devops-tools-installjenkins.qmd
            - devops/devops-tools-installmaven.qmd
        - text: "---"      
        - section: "DevOps Laboratories"
          contents: 
            - devops/devops-lab-chatapp.qmd
            - devops/devops-lab-springbooksintro.qmd
            - devops/devops-lab-springbookss3.qmd
            - devops/devops-lab-springbooksdocker.qmd
            - devops/devops-lab-k8sdigitalocean.qmd
        - text: "---"  
        - section: "DevOps readings"
          contents: 
            - devops/resources.qmd

    - id: "markup"
      title: "MarkUp"
      contents: 
        - text: "MarkUp Languages and Styling"
        - text: "---"  
        - section: "MarkUp Languages"
          contents: 
            - markup/markup-lang-intro.qmd
            - markup/markup-lang-html.qmd
            - markup/markup-lang-md.qmd
            - markup/markup-lang-html-md.qmd
        - text: "---"
        - section: "Quarto Markdown"
          contents: 
            - markup/markup-quarto-basics.qmd
            - markup/markup-quarto-create.qmd
            - markup/markup-quarto-publish.qmd
            - markup/markup-quarto-code.qmd
            - markup/markup-quarto-cheatsheet.qmd
        - text: "---"
        - section: "Styling: CSS"
          contents:
            - markup/markup-css-basics.qmd
            - markup/markup-css-w3css.qmd
        - text: "---"
        - section: "MarkUp Languages Laboratories"
          contents:
            - markup/mulab1.qmd
        - text: "---"
        - section: "MarkUp Languages readings"
          contents:
            - markup/resources.qmd
            
    - id: "javase"
      title: "Java SE"
      contents: 
        - text: "Java Standard Edition"
        - text: "---"  
        - section: "What is Java SE"
          contents: 
            - javase/se-what-basics.qmd
            - javase/se-what-principles.qmd
            - javase/se-what-moochelsinki.qmd
        - text: "---"
        - section: "Java Concepts"
          contents:
            - javase/se-concepts-maven.qmd
            - javase/se-concepts-createproject.qmd
            - javase/se-concepts-projectgit.qmd
            - javase/se-concepts-tdd.qmd
            - javase/se-concepts-objects.qmd
            - javase/se-concepts-scope.qmd
            - javase/se-concepts-static.qmd
            - javase/se-concepts-coupling.qmd
            - javase/se-concepts-package.qmd
        - text: "---"
        - section: "Java Principles"
          contents:
            - javase/se-principles-encapsulation.qmd
            - javase/se-principles-abstraction.qmd
            - javase/se-principles-inheritance.qmd
            - javase/se-principles-polymorphism.qmd
        - text: "---"  
        - section: "Java Design Patterns"
          contents: 
            - javase/se-pattern-intro.qmd
            - javase/se-pattern-uml.qmd
            - javase/se-pattern-singleton.qmd
            - javase/se-pattern-factory.qmd
            - javase/se-pattern-abstractfactory.qmd
            - javase/se-pattern-observer.qmd
            - javase/se-pattern-builder.qmd
        - text: "---"  
        - section: "Java SE Laboratories"
          contents: 
            - javase/selab1-1.qmd
            - javase/selab1-2.qmd
            - javase/selab2-1.qmd
            - javase/selab2-2.qmd
            - javase/selab2-3.qmd
        - text: "---" 
        - section: "Java SE readings"
          contents: 
            - javase/resources.qmd

    - id: "spring"
      title: "Spring"
      contents:
        - text: "Spring"
        - text: "---"  
        - section: "Spring Legacy"
          contents: 
            - spring/spring.qmd
            - spring/springmvc.qmd
        - text: "---"  
        - section: "Spring Boot"
          contents: 
            - springboot/springboot.qmd
        - text: "---"  
        - section: "Spring Boot Laboratories"
          contents: 
            - springboot/sblab1.qmd
            - springboot/sblab2.qmd
            - springboot/sblab3.qmd
            - springboot/sblab4.qmd
            - springboot/sblab5.qmd
        - text: "---" 
        - section: "Spring Boot readings"
          contents: 
            - springboot/resources.qmd
        
    - id: "reactjs"
      title: "ReactJS"
      contents: 
        - text: "ReactJS"
        - text: "---"  
        - section: "ReactJS: Principles"
          contents: 
            - reactjs/reactjs-what-principles.qmd
            - reactjs/reactjs-what-render-dom.qmd
            - reactjs/reactjs-what-create.qmd
            - reactjs/reactjs-what-components.qmd
            - reactjs/reactjs-what-jsx.qmd
            - reactjs/reactjs-what-props.qmd
        - text: "---"  
        - section: "ES6: ECMAScript 6"
          contents: 
            - reactjs/reactjs-es6-arrow.qmd
            - reactjs/reactjs-es6-import.qmd
            - reactjs/reactjs-es6-data.qmd
            - reactjs/reactjs-es6-destructuring.qmd
            - reactjs/reactjs-es6-spread.qmd
        - text: "---"  
        - section: "ReacJS 18: Hooks"
          contents: 
            - reactjs/reactjs-hook-state.qmd
            - reactjs/reactjs-hook-reducer.qmd
            - reactjs/reactjs-hook-ref.qmd
            - reactjs/reactjs-hook-effect.qmd
            - reactjs/reactjs-hook-custom.qmd
            - reactjs/reactjs-hook-context.qmd
        - text: "---"  
        - section: "ReactJS: Designing an App"
          contents: 
            - reactjs/reactjs-app-async.qmd
            - reactjs/reactjs-app-events.qmd
            - reactjs/reactjs-app-router.qmd
            - reactjs/reactjs-app-conditional-render.qmd
            - reactjs/reactjs-app-styling.qmd
        - text: "---"  
        - section: "React JS: Laboratories"
          contents: 
            - reactjs/rjslab1.qmd
            - reactjs/rjslab2.qmd
            - reactjs/rjslab3.qmd
            - reactjs/rjslab4.qmd
            - reactjs/rjslab5.qmd
        - text: "---" 
        - section: "React JS readings"
          contents: 
            - reactjs/resources.qmd

    - id: "scrum"
      title: "SCRUM"
      contents: 
        - text: "SCRUM"
        - text: "---"  
        - section: "What is SCRUM"
          contents: 
            - scrum/scrum-what-concepts.qmd
            - scrum/scrum-what-agile-manifesto.qmd
            - scrum/scrum-what-guide.qmd
        - text: "---"  
        - section: "Weeks"
          contents:
            - scrum/scrum-week1.qmd
            - scrum/scrum-week2.qmd
            - scrum/scrum-week3.qmd
            - scrum/scrum-week4.qmd
            - scrum/scrum-week5.qmd
            - scrum/scrum-week6.qmd
            - scrum/scrum-week7.qmd
            - scrum/scrum-week8.qmd
        - text: "---"  
        - section: "Resources"
          contents:
             - scrum/resources.qmd

    - id: "vocabulary"
      title: "Vocabulary"
      contents: 
        - text: "Vocabulary"
        - text: "---"  
        - section: "General Vocabulary"
          contents: 
            - vocabulary/vocab-general.qmd
            - vocabulary/vocab-scrum.qmd
            - vocabulary/vocab-devops.qmd
        - text: "---"  
        - section: "Back-end Vocabulary"
          contents: 
            - vocabulary/vocab-java-se.qmd
            - vocabulary/vocab-spring-boot.qmd
            - vocabulary/vocab-data-base.qmd
        - text: "---"  
        - section: "Front-end Vocabulary"
          contents: 
            - vocabulary/vocab-reactjs.qmd
            - vocabulary/vocab-web.qmd
            
    - id: "ifcd"
      title: "IFCD0210"
      contents: 
        - text: "IFCD0210"
        - text: "---"  
        - section: "Web App IFCD0210"
          contents: 
            - ifcd0210/ifcd0210.qmd
            - ifcd0210/ifcd0210calendar.qmd
            - ifcd0210/ifcd0210initemail.qmd
            - ifcd0210/ifcd0210deliveries.qmd

    - id: "about"
      title: "About"
      contents: 
        - text: "About"
        - text: "---"  
        - section: "About me and this site"
          contents: 
            - about/about-this-me.qmd
            - about/about-this-site.qmd
            - about/about-this-images-credit.qmd
        - text: "---"
        - section: "Learning"
          contents: 
            - about/about-learning-intro.qmd
            - about/about-learning-questions.qmd
        - text: "---"
        - section: "Listings"
          contents: 
            - about/about-listing-table.qmd
            - about/about-listing-card.qmd

  page-footer: 
    background: dark
    left: "[Attribution 4.0 International (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/)" 
    center: "if you want to go far, walk slow" 
    right: 
      - icon: github
        href: https://github.com/AlbertProfe/
      - icon: twitter 
        href: https://twitter.com/ 
